(() => {
'use strict';
const APP_KEY='riftbound-vault-v2', XLSX_SRC='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';
const PH=new Set(['','blank','missing','empty','n/a','na','none','null','placeholder','tbd','-','--']);
const AL={code:['card code','cardcode','code','id'],number:['card number','cardnumber','collector number','number','no','#'],set:['set code','setcode','card set','set','expansion'],name:['card name','cardname','full name','name'],qty:['quantity owned','quantity','qty','owned','copies','count']};
let book=null,rows=[],fileName='',map={code:'',number:'',set:'',name:'',qty:''},analysis=null,ri=0,search='';
const esc=(v='')=>String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘`´]/g,"'").replace(/[_-]+/g,' ').replace(/\s+/g,' ');
const key=v=>norm(v).replace(/[^a-z0-9]/g,'');
const cardName=c=>c?.fullName||c?.name||c?.cardCode||'Unknown card';
const meaningful=v=>!PH.has(norm(v));
const qty=v=>{if(v===''||v==null)return 1;const n=Number(String(v).replace(/,/g,'').trim());return Number.isFinite(n)?Math.max(0,Math.floor(n)):0};
const uid=()=>`evt-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const readState=()=>{try{return JSON.parse(localStorage.getItem(APP_KEY)||'{}')}catch{return {}}};
const dedupe=a=>[...new Map((a||[]).filter(Boolean).map(c=>[c.cardCode,c])).values()];
function ensureUI(){
 const panel=document.getElementById('uxSettings');
 if(panel&&!document.getElementById('spreadsheetImportSetting')){const r=document.createElement('div');r.id='spreadsheetImportSetting';r.className='setting-row spreadsheet-import-setting';r.innerHTML='<div class="setting-copy"><strong>Import spreadsheet</strong><small>Excel/CSV import with alternate-art quantity splitting.</small></div><button id="openSpreadsheetImport" class="sound-test" type="button">Import</button>';panel.appendChild(r)}
 if(document.getElementById('spreadsheetImportDialog'))return;
 const d=document.createElement('dialog');d.id='spreadsheetImportDialog';d.className='modal spreadsheet-import-dialog';d.innerHTML=`<div class="modal-inner spreadsheet-import-inner"><div class="modal-head"><div><h2>Import Spreadsheet</h2><p class="spreadsheet-subtitle">Excel / CSV → Riftbound Vault</p></div><button class="close-btn" data-close-sheet>×</button></div><div id="sheetDrop" class="spreadsheet-drop"><input id="sheetFile" type="file" accept=".xlsx,.xls,.csv,.xlsb,.ods" hidden><div class="spreadsheet-drop-icon">✦</div><strong>Choose an Excel or CSV file</strong><span>or drag and drop it here</span><button id="chooseSheet" class="primary-btn" type="button">Choose File</button></div><div id="sheetWork" hidden><div class="spreadsheet-filebar"><div><strong id="sheetName"></strong><small id="sheetRows"></small></div><button id="changeSheet" class="ghost-btn">Change File</button></div><div class="spreadsheet-grid-two"><label>Sheet<select id="sheetSelect"></select></label><label>Import mode<select id="sheetMode"><option value="add">Add quantities to collection</option><option value="set">Set owned quantities for matched cards</option></select></label></div><div class="spreadsheet-mapping-wrap"><div class="spreadsheet-section-head"><div><h3>Column Mapping</h3><p>Auto-detected where possible.</p></div></div><div id="sheetMap" class="spreadsheet-mapping"></div></div><div id="sheetSummary" class="spreadsheet-summary spreadsheet-summary-v3"></div><div id="sheetReview" class="spreadsheet-review-actions" hidden><div><strong id="sheetReviewText"></strong><small>Split quantities between alternate arts if needed.</small></div><button id="reviewSheet" class="primary-btn">Review Problem Cards</button></div><div class="spreadsheet-preview-wrap"><div class="spreadsheet-section-head"><div><h3>Preview</h3><p>Blank/missing placeholder rows are ignored.</p></div><button id="sheetProblems" class="ghost-btn">Show Problems</button></div><div id="sheetPreview" class="spreadsheet-preview"></div></div><div id="sheetMsg" class="feature-message"></div><div class="modal-actions spreadsheet-actions"><button id="sheetImport" class="primary-btn" disabled>Import Matched Cards</button></div></div></div>`;document.body.appendChild(d);
 const r=document.createElement('dialog');r.id='sheetResolver';r.className='modal spreadsheet-resolver-dialog';r.innerHTML='<div id="sheetResolverInner" class="modal-inner spreadsheet-resolver-inner"></div>';document.body.appendChild(r);
}
function loadXLSX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((ok,bad)=>{const s=document.createElement('script');s.src=XLSX_SRC;s.onload=()=>window.XLSX?ok(window.XLSX):bad(new Error('Spreadsheet reader failed'));s.onerror=()=>bad(new Error('Could not load spreadsheet reader'));document.head.appendChild(s)})}
function detect(headers){const out={code:'',number:'',set:'',name:'',qty:''},hs=headers.map(h=>({r:h,n:norm(h),k:key(h)}));for(const [f,als] of Object.entries(AL)){const hit=hs.find(h=>als.some(a=>h.n===norm(a)||h.k===key(a)));if(hit)out[f]=hit.r}return out}
function renderMap(){const root=document.getElementById('sheetMap');if(!root)return;const hs=rows.length?Object.keys(rows[0]):[];const defs=[['code','Card code'],['number','Card number'],['set','Set'],['name','Card name'],['qty','Quantity']];root.innerHTML=defs.map(([f,l])=>`<label><span><strong>${l}</strong></span><select data-map="${f}"><option value="">Not provided</option>${hs.map(h=>`<option ${map[f]===h?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`).join('')}
function numKeys(v){const raw=String(v??'').trim();if(!meaningful(raw))return[];const s=new Set([key(raw)]),m=raw.match(/^(?:\D*)(\d+)(.*)$/);if(m){s.add(String(Number(m[1])));s.add(`${Number(m[1])}${key(m[2])}`)}return[...s].filter(Boolean)}
function indexes(catalog){const o={codes:new Map(),nums:new Map(),setNums:new Map(),names:new Map(),setNames:new Map()};const push=(m,k,c)=>{if(!k)return;const a=m.get(k)||[];if(!a.some(x=>x.cardCode===c.cardCode))a.push(c);m.set(k,a)};catalog.forEach(c=>{o.codes.set(key(c.cardCode),c);const sets=[c.setCode,c.cardSet,c.setName].filter(Boolean).map(key);numKeys(c.cardNumber).forEach(n=>{push(o.nums,n,c);sets.forEach(s=>push(o.setNums,`${s}|${n}`,c))});push(o.names,key(cardName(c)),c);sets.forEach(s=>push(o.setNames,`${s}|${key(cardName(c))}`,c))});return o}
function candidate(cards,method){cards=dedupe(cards);if(cards.length===1)return{status:'matched',method,candidates:cards,assignments:[{card:cards[0],qty:null}]};if(cards.length>1)return{status:'review',method,candidates:cards,assignments:[]};return null}
function placeholderRow(row){const vals=[map.code,map.number,map.name].filter(Boolean).map(c=>row[c]);return !vals.length||vals.every(v=>!meaningful(v))}
function match(row,idx,catalog){if(placeholderRow(row))return{status:'ignored',method:'Placeholder',candidates:[],assignments:[]};const code=map.code&&meaningful(row[map.code])?row[map.code]:'',num=map.number&&meaningful(row[map.number])?row[map.number]:'',set=map.set&&meaningful(row[map.set])?row[map.set]:'',name=map.name&&meaningful(row[map.name])?row[map.name]:'';const sk=key(set);
 if(code){const c=idx.codes.get(key(code));if(c)return{status:'matched',method:'Card code',candidates:[c],assignments:[{card:c,qty:null}]}}
 if(num&&sk){let a=[];numKeys(num).forEach(n=>a.push(...(idx.setNums.get(`${sk}|${n}`)||[])));const r=candidate(a,'Set + number');if(r)return r}
 if(name&&sk){const r=candidate(idx.setNames.get(`${sk}|${key(name)}`)||[],'Set + name');if(r)return r}
 if(num){let a=[];numKeys(num).forEach(n=>a.push(...(idx.nums.get(n)||[])));const r=candidate(a,'Card number');if(r)return r}
 if(name){const r=candidate(idx.names.get(key(name))||[],'Card name');if(r)return r;const k=key(name),a=dedupe(catalog.filter(c=>k.length>=4&&(key(cardName(c)).includes(k)||k.includes(key(cardName(c)))))).slice(0,12);if(a.length===1)return{status:'matched',method:'Unique name suggestion',candidates:a,assignments:[{card:a[0],qty:null}]};if(a.length>1)return{status:'review',method:'Possible name matches',candidates:a,assignments:[]}}
 return{status:'unmatched',method:'Unmatched',candidates:[],assignments:[]}}
function rebuild(items){const ag=new Map();let matched=0,review=0,unmatched=0,ignored=0,total=0;items.forEach(it=>{if(it.status==='ignored'){ignored++;return}if(it.status==='review'){review++;return}if(it.status==='unmatched'){unmatched++;return}matched++;it.assignments.forEach(a=>{const q=Math.max(0,Number(a.qty||0));total+=q;if(!q)return;const x=ag.get(a.card.cardCode)||{card:a.card,qty:0};x.qty+=q;ag.set(a.card.cardCode,x)})});return{aggregate:ag,matched,review,unmatched,ignored,total,unique:ag.size}}
function analyze(){const catalog=window.RiftboundApp?.getCatalog?.()||[],idx=indexes(catalog),items=[];rows.forEach((row,i)=>{const q=qty(map.qty?row[map.qty]:'');const r=match(row,idx,catalog),it={row:i+2,rowData:row,qty:q,...r};if(it.status==='matched'&&it.assignments.length===1&&it.assignments[0].qty==null)it.assignments[0].qty=q;items.push(it)});analysis={items,...rebuild(items)};renderAnalysis()}
function label(it){return[map.name&&it.rowData[map.name],map.set&&it.rowData[map.set],map.number&&it.rowData[map.number]].filter(v=>meaningful(v)).join(' • ')||'(placeholder / blank)'}
function renderAnalysis(problems=false){const a=analysis||{items:[],matched:0,review:0,unmatched:0,ignored:0,total:0,unique:0};document.getElementById('sheetSummary').innerHTML=`<div><strong>${rows.length}</strong><small>Rows</small></div><div class="good"><strong>${a.matched}</strong><small>Matched</small></div><div class="${a.review?'warn':''}"><strong>${a.review}</strong><small>Needs review</small></div><div class="${a.unmatched?'warn':''}"><strong>${a.unmatched}</strong><small>Unmatched</small></div><div class="muted"><strong>${a.ignored}</strong><small>Ignored</small></div><div><strong>${a.total}</strong><small>Copies ready</small></div>`;const rev=document.getElementById('sheetReview');rev.hidden=!a.review;if(a.review)document.getElementById('sheetReviewText').textContent=`${a.review} row${a.review===1?'':'s'} need your choice`;
 const list=a.items.filter(x=>!problems||x.status==='review'||x.status==='unmatched').slice(0,100);document.getElementById('sheetPreview').innerHTML=`<div class="spreadsheet-table"><div class="spreadsheet-tr spreadsheet-th"><span>Row</span><span>Spreadsheet</span><span>Assignment</span><span>Qty</span><span>Status</span></div>${list.map(it=>{let as=it.status==='matched'?it.assignments.map(a=>`${esc(cardName(a.card))} ×${a.qty}`).join('<br>'):it.status==='review'?`${it.candidates.length} possible cards`:it.status==='ignored'?'Ignored placeholder':'No safe match';return`<div class="spreadsheet-tr ${it.status}"><span>${it.row}</span><span>${esc(label(it))}</span><span>${as}</span><span>${it.qty}</span><span>${it.status==='matched'?'✓ Matched':it.status==='review'?'? Review':it.status==='ignored'?'○ Ignored':'! Unmatched'}</span></div>`}).join('')}</div>`;document.getElementById('sheetImport').disabled=!a.matched||a.review>0;document.getElementById('sheetMsg').textContent=a.review?`Review ${a.review} ambiguous row${a.review===1?'':'s'}. Single-choice matches were assigned automatically.`:a.unmatched?`${a.unmatched} unmatched row${a.unmatched===1?'':'s'} will be skipped. ${a.ignored} placeholder row${a.ignored===1?' was':'s were'} ignored.`:`Ready to import. ${a.ignored} placeholder row${a.ignored===1?' was':'s were'} ignored.`}
const reviewItems=()=>analysis?.items?.filter(x=>x.status==='review')||[];
function resolverCards(it){let a=dedupe(it.candidates);if(search){const q=key(search),cat=window.RiftboundApp?.getCatalog?.()||[];a=dedupe([...a,...cat.filter(c=>key(`${cardName(c)} ${c.cardSet||''} ${c.cardNumber||''}`).includes(q)).slice(0,30)])}return a}
function renderResolver(){const ps=reviewItems();if(!ps.length){document.getElementById('sheetResolver').close();renderAnalysis();return}ri=Math.max(0,Math.min(ri,ps.length-1));const it=ps[ri],assigned=it.assignments.reduce((n,a)=>n+Number(a.qty||0),0),remain=it.qty-assigned;document.getElementById('sheetResolverInner').innerHTML=`<div class="modal-head"><div><h2>Choose the right printing</h2><p class="spreadsheet-subtitle">Problem ${ri+1} of ${ps.length} • Row ${it.row}</p></div><button class="close-btn" data-close-resolver>×</button></div><div class="resolver-row-summary"><div><small>Spreadsheet</small><strong>${esc(label(it))}</strong></div><div><small>Total copies</small><strong>${it.qty}</strong></div><div class="${remain===0?'good':'warn'}"><small>Still to assign</small><strong>${remain}</strong></div></div><p class="resolver-help">Split this row across as many splash arts/printings as you own. The total must equal <strong>${it.qty}</strong>.</p><div class="feature-search"><input id="resolverSearchV4" value="${esc(search)}" placeholder="Search full catalog"></div><div class="resolver-candidates">${resolverCards(it).map(c=>{const cur=it.assignments.find(a=>a.card.cardCode===c.cardCode)?.qty||0;return`<article class="resolver-candidate">${c.imageUrl?`<img src="${esc(c.imageUrl)}" alt="">`:''}<div class="resolver-candidate-copy"><strong>${esc(cardName(c))}</strong><small>${esc(c.cardSet||'')} • ${esc(c.cardNumber||'')} • ${esc(c.rarity||'')}</small><label>Copies<input type="number" min="0" max="${it.qty}" value="${cur}" data-resolver-qty="${esc(c.cardCode)}"></label><button class="ghost-btn" data-resolver-all="${esc(c.cardCode)}">Assign all ${it.qty}</button></div></article>`}).join('')}</div><div class="resolver-footer"><button class="ghost-btn" data-ignore-row>Ignore row</button><button class="primary-btn" data-save-row ${remain!==0?'disabled':''}>Save & Next</button></div>`}
function setAssign(code,n){const it=reviewItems()[ri],card=(window.RiftboundApp?.getCatalog?.()||[]).find(c=>c.cardCode===code);if(!it||!card)return;n=Math.max(0,Math.min(it.qty,Math.floor(Number(n)||0)));it.assignments=it.assignments.filter(a=>a.card.cardCode!==code);if(n)it.assignments.push({card,qty:n});renderResolver()}
function saveRow(){const it=reviewItems()[ri];if(!it||it.assignments.reduce((n,a)=>n+Number(a.qty||0),0)!==it.qty)return;it.status='matched';it.method=it.assignments.length>1?'Split between printings':'Chosen printing';analysis={items:analysis.items,...rebuild(analysis.items)};search='';if(reviewItems().length)renderResolver();else document.getElementById('sheetResolver').close();renderAnalysis()}
function ignoreRow(){const it=reviewItems()[ri];if(!it)return;it.status='ignored';it.assignments=[];analysis={items:analysis.items,...rebuild(analysis.items)};search='';if(reviewItems().length)renderResolver();else document.getElementById('sheetResolver').close();renderAnalysis()}
function loadSheet(name){const ws=book.Sheets[name];rows=window.XLSX.utils.sheet_to_json(ws,{defval:'',raw:false,blankrows:false});map=detect(rows.length?Object.keys(rows[0]):[]);document.getElementById('sheetRows').textContent=`${rows.length} data rows`;renderMap();analyze()}
async function openFile(file){if(!file)return;try{fileName=file.name;const XLSX=await loadXLSX(),data=await file.arrayBuffer();book=XLSX.read(data,{type:'array'});document.getElementById('sheetSelect').innerHTML=book.SheetNames.map(n=>`<option>${esc(n)}</option>`).join('');document.getElementById('sheetName').textContent=fileName;document.getElementById('sheetDrop').hidden=true;document.getElementById('sheetWork').hidden=false;loadSheet(book.SheetNames[0])}catch(e){alert(`Could not read spreadsheet: ${e.message}`)}}
function allocated(code,s){return(s.decks||[]).reduce((n,d)=>n+Number(d.cards?.[code]||0),0)+(s.loans||[]).filter(l=>!l.returnedAt&&l.cardCode===code).reduce((n,l)=>n+Number(l.qty||0),0)}
function applyImport(){if(!analysis?.aggregate?.size||analysis.review)return;const mode=document.getElementById('sheetMode').value,s={inventory:{},decks:[],loans:[],transactions:[],...readState()};let changed=0;for(const [code,x] of analysis.aggregate){const cur=Number(s.inventory?.[code]?.owned||0),min=allocated(code,s),next=Math.max(min,mode==='set'?x.qty:cur+x.qty);s.inventory=s.inventory||{};if(next!==cur){s.inventory[code]={...(s.inventory[code]||{}),owned:next};changed++}}s.transactions=[{id:uid(),type:'activity',action:`Imported spreadsheet “${fileName}” • ${changed} cards updated`,at:new Date().toISOString(),source:'spreadsheet',ignoredRows:analysis.ignored},...(s.transactions||[])].slice(0,500);localStorage.setItem(APP_KEY,JSON.stringify(s));window.RiftboundApp?.reloadState?.();window.RiftboundCloud?.syncNow?.();document.getElementById('sheetMsg').textContent=`Import complete: ${changed} unique cards updated.`}
function reset(){book=null;rows=[];analysis=null;search='';map={code:'',number:'',set:'',name:'',qty:''};document.getElementById('sheetDrop').hidden=false;document.getElementById('sheetWork').hidden=true;document.getElementById('sheetFile').value=''}
function bind(){document.addEventListener('click',e=>{if(e.target.closest('#openSpreadsheetImport')){reset();document.getElementById('spreadsheetImportDialog').showModal()}else if(e.target.closest('[data-close-sheet]'))document.getElementById('spreadsheetImportDialog').close();else if(e.target.closest('[data-close-resolver]'))document.getElementById('sheetResolver').close();else if(e.target.closest('#chooseSheet')||e.target.closest('#changeSheet'))document.getElementById('sheetFile').click();else if(e.target.closest('#reviewSheet')){ri=0;search='';renderResolver();document.getElementById('sheetResolver').showModal()}else if(e.target.closest('#sheetImport'))applyImport();else if(e.target.closest('#sheetProblems')){const b=e.target.closest('#sheetProblems'),on=b.dataset.on!=='1';b.dataset.on=on?'1':'0';b.textContent=on?'Show All':'Show Problems';renderAnalysis(on)}else if(e.target.closest('[data-resolver-all]'))setAssign(e.target.closest('[data-resolver-all]').dataset.resolverAll,reviewItems()[ri]?.qty||0);else if(e.target.closest('[data-save-row]'))saveRow();else if(e.target.closest('[data-ignore-row]'))ignoreRow()});document.addEventListener('change',e=>{if(e.target.id==='sheetFile')openFile(e.target.files?.[0]);else if(e.target.id==='sheetSelect')loadSheet(e.target.value);else if(e.target.matches('[data-map]')){map[e.target.dataset.map]=e.target.value;analyze()}else if(e.target.matches('[data-resolver-qty]'))setAssign(e.target.dataset.resolverQty,e.target.value)});document.addEventListener('input',e=>{if(e.target.id==='resolverSearchV4'){search=e.target.value;clearTimeout(window.__rbst);window.__rbst=setTimeout(renderResolver,120)}})}
function init(){ensureUI();bind();new MutationObserver(ensureUI).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();